Fix the khronos cts test runner infra dependency errors
This change does below fixes so that we can launch the
KhronosCTSTestCases on Android bot devices with an ATP
config V2 GCL file:
https://critique.corp.google.com/cl/606712422/depot/google3/configs/wireless/android/testing/atp/prod/angle-for-android/KhronosCTS/git_main.gcl

1. Add dependency to DeqpTestRunner through
static_lib of a java_library_host, to fix
the tradefed runner runtime error:
`java.lang.NoClassDefFoundError: com/drawelements/deqp/runner/DeqpTestRunner`
http://go/forrest-run/L42800030006152661

2.Add the `test_suites: ["general-tests"]` tag to
KhronosCTSTestCases target, to fix the tradefed runner
not able to find the test KhronosCTSTestCases error:
http://go/forrest-run/L65500030006136532

3. Check mTestRunParams and mTestInstances are
not null before calling functions that initialize their
contents. Tradefed runner runs the KhronosCTSTestCases
more than once, this guards against "assertion error:
re-load of test run params not supported":
https://android-build.corp.google.com/abtd/run/L82200030006221150/

Ignore-Khronos-First: test runners affected by code change is
meant for internal testing only. No other khronos members should
need the code change

Test: atest KhronosCTSTestCases
Test: https://android-build.corp.google.com/abtd/run/L21000030006241478/. Invocation succeeds. Test failure in the invocation is expected.
Bug: b/306750271
Change-Id: Ic3639f46c5eb6412c1167c6b85dc09c71a68fcc3