Include sys/system_properties.h in teglAndroidUtil.cpp
The following CL added a call to __system_property_get():
https://github.com/KhronosGroup/VK-GL-CTS/commit/8a537a0c916e1a10e134f648801f0812c4c749ba

However, it's failing to build:

  ../../third_party/angle/third_party/VK-GL-CTS/src/modules/egl/teglAndroidUtil.cpp:78:3:
  error: use of undeclared identifier '__system_property_get'
                __system_property_get("ro.build.version.sdk", value);

This is caused by teglAndroidUtil.cpp not including
sys/system_properties.h. Including the file fixes the error.

Change-Id: I0e63fcc9dfe0e872832da07e3b8d7f2f78f9d835
(cherry picked from commit 968b6ee77b11267cb6afb6fdbd9bef847eb14868)